# File: .github/workflows/main_careervault.yml

name: Build and Deploy React App to Azure Web App - CAREERVAULT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies and build React app
      - name: Install Dependencies & Build
        working-directory: ./my-app
        run: |
          npm install
          npm run build --if-present

      # Upload the build artifact for deployment
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: ./my-app/build

  deploy:
    name: Deploy React App to Azure Web App
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read

    steps:
      # Download the build artifact
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build
          path: ./my-app/build

      # Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CAREERVAULT'
          slot-name: 'Production'
          package: ./my-app/build
