name: Build and Deploy React App - CAREERVAULT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        working-directory: ./my-app
        run: |
          npm install
          npm run build --if-present

      - name: Azure Login using Service Principal
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5C764ED0A0D0472CAF383A84C88CA888 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_090FDCF8BAAF47878EB40F705AF8D966 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BF8E25864AD645F587CE91E085FDDD0E }}
          auth-type: service-principal

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CAREERVAULT'
          slot-name: 'Production'
          package: ./my-app/build
