name: Terraform CI/CD - CAREERVAULT

on:
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.6'

      # 4️⃣ Initialize Terraform
      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=rg-terraform" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=infrastructure.tfstate"

      # 5️⃣ Format Check
      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      # 6️⃣ Validate
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      # 7️⃣ Plan
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      # 8️⃣ Apply automatically
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve ./tfplan

      # 9️⃣ Optional: Upload Apply Logs
      - name: Upload Apply Logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-logs
          path: ./terraform/terraform_apply.log || true
