name: Terraform CI/CD - CAREERVAULT Infrastructure

on:
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: 'SERVICE_PRINCIPAL'
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.6'

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=rg-terraform" \
            -backend-config="storage_account_name=tfstatecareervault01" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Upload Plan Output
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./terraform/plan.txt

  apply:
    name: Terraform Apply (Requires Approval)
    needs: plan
    runs-on: ubuntu-latest
    environment: production  # manual approval required

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./terraform

      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: 'SERVICE_PRINCIPAL'
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.6'

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=rg-terraform" \
            -backend-config="storage_account_name=tfstatecareervault01" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=terraform.tfstate"

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve tfplan | tee terraform_apply.log

      - name: Upload Apply Logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-logs
          path: ./terraform/terraform_apply.log
