name: Terraform CI/CD - CAREERVAULT

on:
  push:
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.6'

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=rg-terraform" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=infrastructure.tfstate"

      - name: Terraform Format Check
        working-directory: ./terraform
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./terraform/tfplan

  apply:
    name: Terraform Apply (Requires Approval)
    needs: plan
    runs-on: ubuntu-latest
    environment: production  # GitHub will require manual approval

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./terraform

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.6'

      - name: Terraform Init
        working-directory: ./terraform
        run: |
          terraform init -input=false \
            -backend-config="resource_group_name=rg-terraform" \
            -backend-config="storage_account_name=${{ secrets.TFSTATE_STORAGE_ACCOUNT }}" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=infrastructure.tfstate"

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve ./tfplan

      - name: Upload Apply Logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-apply-logs
          path: ./terraform/terraform_apply.log || true
